### PR TITLE
Feature: enhance zipped submissions support

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
## Changes

- Add gzipped submissions support
- Fix diff process not working for zipped submissions (https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/12)
- Fix a bug when generating the output folder path for the diff file (https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/13)
- add the zipped? and parsable? functions to the submissions to know respectively if the submission is zipped and can be parsed. 
- Some code refactoring

### CODE REVIEW

**Comment by alexskr** [comment]
Is it worth adding a unit test for zipped file submission?

**Comment by syphax-bouazzouni** [comment]
> Is it worth adding a unit test for zipped file submission?

Yeah indeed, I will do it. (you don't have a lot of gzipped resources in Bioportal, but some zip (22))
In the future, resources will be bigger and bigger, and a lot will be zipped, so yeah being solid on that would be necessary.

 
Anyway, in my following PRs, I will do specific tests for each of them (now that I master more our system of tests)

**Comment by syphax-bouazzouni** [comment]
> ```diff
> - Misses        935      944       +9    
> ```
I love this system of Codecov Report, great work @alexskr (any plans for other GitHub actions on your side?)

**Comment by alexskr** [comment]
> I love this system of Code coverage Report, great work @alexskr (any plans for other GitHub actions on your side?)

yes, the plan is to enable code coverage reports on most projects

**Comment by mdorf** [comment]
I have not had the chance to investigate the issue, but one of our colleagues from RADx tried submitting an ontology in GZIP (.GZ) format, and the parsing failed. When he re-submitted it as a ZIP file, the parsing succeeded. At this point, I don't have the bandwidth to investigate further; just wanted to place a note of this behavior.

**Comment by alexskr** [comment]
gzipped ontology submission gets processes correctly when run with ncbo_process_ontology script in ncbo_cron project but fails when it is run as a ncbo_cron job.  I think https://github.com/ncbo/ncbo_cron/pull/55 is supposed to fix this.

**Pull request merged**
