### PR TITLE
Feature: extract ontology URI automatically in submissions process

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
### Prerequisite

- https://github.com/ncbo/owlapi_wrapper/pull/17

### What
This PR will fix https://github.com/ncbo/ontologies_linked_data/issues/152

### CODE REVIEW

**Comment by mdorf** [comment]
This pull request has been merged into the https://github.com/ncbo/ontologies_linked_data/tree/develop branch

**Comment by mdorf** [comment]
@syphax-bouazzouni this PR is missing code. The method `generate_rdf` has changed from accepting two arguments to accepting three arguments:
FROM:
def generate_rdf(logger, reasoning: true)
TO
def generate_rdf(logger, file_path, reasoning=true)

But the source of the new `generate_rdf` and calls to it with three arguments are not included in the PR.

```
  1) Error:
TestSearchController#test_search_obo_id:
ArgumentError: wrong number of arguments (given 3, expected 1)
    /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/models/ontology_submission.rb:452:in `generate_rdf'
    /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/models/ontology_submission.rb:1005:in `process_submission'
    /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:117:in `block (2 levels) in create_ontologies_and_submissions'
    /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:109:in `each'
    /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:109:in `block in create_ontologies_and_submissions'
    /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:107:in `each'
    /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:107:in `create_ontologies_and_submissions'
    /Users/mdorf/dev/ncbo/ontologies_api/test/controllers/test_search_controller.rb:207:in `test_search_obo_id'
```

**Comment by mdorf** [comment]
merged manually to develop

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni this PR is missing code. The method `generate_rdf` has changed from accepting two arguments to accepting three arguments: FROM: def generate_rdf(logger, reasoning: true) TO def generate_rdf(logger, file_path, reasoning=true)
> 
> But the source of the new `generate_rdf` and calls to it with three arguments are not included in the PR.
> 
> ```
>   1) Error:
> TestSearchController#test_search_obo_id:
> ArgumentError: wrong number of arguments (given 3, expected 1)
>     /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/models/ontology_submission.rb:452:in `generate_rdf'
>     /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/models/ontology_submission.rb:1005:in `process_submission'
>     /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:117:in `block (2 levels) in create_ontologies_and_submissions'
>     /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:109:in `each'
>     /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:109:in `block in create_ontologies_and_submissions'
>     /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:107:in `each'
>     /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/sample_data/ontology.rb:107:in `create_ontologies_and_submissions'
>     /Users/mdorf/dev/ncbo/ontologies_api/test/controllers/test_search_controller.rb:207:in `test_search_obo_id'
> ```

Have you been able to figure out this? this PR had not changed `generate_rdf`, maybe the upstream code changed since the creation of this PR.

**Comment by mdorf** [comment]
Yes, I was able to track down the missing code. The method `generate_rdf` had changed at some point to accept an extra argument to store the `file_path`, which is required by this PR to be passed to the OWL API Wrapper for extracting the ontology IRI.

**Pull request closed without merging**
