### PR TITLE
Refactor: ontology_submission.rb file to isolate the processing steps 

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
## Why 
The current model [ontologies_submission.rb](https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb) (which represents the submission concept) contains more than 1500 lines, including in the same time the model information (its attributes e.g submissionId)  and the model operations ( e.g parsing, diff, ...).

This PL isolates the different operations into separate modules. Making the ontologies_submission.rb file smaller (600 lines), easier to read and maintain

### CODE REVIEW

**Comment by mdorf** [comment]
manually merged this PR to https://github.com/ncbo/ontologies_linked_data/tree/develop

**Comment by alexskr** [comment]
this PR overwrite metrics calculation changes introduced in https://github.com/ncbo/ontologies_linked_data/pull/182. Those changes need to be re-applied.

**Comment by syphax-bouazzouni** [comment]
Yes, this PR is too old, it needs to be updated.

**Comment by alexskr** [comment]
> this PR overwrite metrics calculation changes introduced in #182. Those changes need to be re-applied.

addressed in https://github.com/ncbo/ontologies_linked_data/commit/da1642ed8f9f04db2e427e35d88f235a55138d03

**Comment by alexskr** [comment]
manually merged

**Comment by syphax-bouazzouni** [comment]
> manually merged

OK great, keep me informed, If support is needed on this.

**Pull request closed without merging**
