### PR TITLE
Solr v8 schema update

### PR DESCRIPTION
**Pull request by alexskr**
update solr schema to be up to date with solr 8.11.2 

- resolves deprecation notices https://github.com/ncbo/ontologies_linked_data/issues/121
- BioPortal configuration is groupped into one section to make future
upgrades easier.

### CODE REVIEW

**Review by syphax-bouazzouni — COMMENTED** [review]
I plan to extend our indexation, to add submission and ontology metadata, as acronyms, and descriptions, ... and I wanted just to ask if it is possible to not have the `schema.xml` files, and just define the schema in the code? this will make it easier to involve and maintain in the future.

**Comment by alexskr** [comment]
ditching hardcoded schema.xml in solr in favor of a programmatic solr schema configuration has been in on our mind for quite a long time.

**Comment by syphax-bouazzouni** [comment]
> ditching hardcoded schema.xml in solr in favor of a programmatic solr schema configuration has been in on our mind for quite a long time. (#118)

I did a first iteration of that, please see https://github.com/ontoportal-lirmm/goo/pull/54

**Comment by alexskr** [comment]
closing in favor of https://github.com/ontoportal-lirmm/goo/pull/54

**Pull request closed without merging**
